In [1]:
import numpy as np


In [2]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
print("shape = ",a.shape)
print("dimension = ",a.ndim)
print("data type = ",a.dtype.name)
print("itemszie = ",a.itemsize)
print("size = ",a.size)
type(a)

b = np.array([6,7,8])
b

shape =  (15,)
dimension =  1
data type =  int32
itemszie =  4
size =  15


array([6, 7, 8])

#  Array Creation

In [18]:
a = np.array([1,2,3,4])

### automatically transform to two-dimensional arrays

b = np.array([(1.5,2,3),(4,5,6)])
print(b)
c = np.array([[1,2],[3,4]],dtype = complex)
c

[[ 1.5  2.   3. ]
 [ 4.   5.   6. ]]


array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [22]:
### create zero array with shape
np.zeros((3,4))

## create one array with shape
np.ones((2,3,4),dtype = int)

np.empty((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

### Sequence of numbers >> np.arange()
###  The result is an np array
### np.arange(s,e,step)

### np.linspace(s,e,number of steps)

In [26]:
print(np.arange(10,30,5))

print(np.linspace(0,2,9))

[10 15 20 25]
[ 0.    0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ]


# Basic Operations

#### Arithmetic operatiors on arrays apply elementwise. New array is created and filled with the result

In [33]:
a = np.array([20,30,40,50])
b = np.arange(4)

c = a-b

print(c)

print(b**2)

print(10*np.sin(a))

print(a<30)

[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True False False False]


##  * >> elementwise multiply
##  dot >> inner product

In [37]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

print(A*B)

print(np.dot(A,B))

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


##  np.sum(), np.min, np.max() --> If not set axis parameter, will apply to the array as though it 

##  were a list of numbers

In [42]:
a = np.random.random((2,3))
print(a)

print(a.sum())
print(a.min())
print(a.max())
print()
b = np.arange(12).reshape(3,4)
print(b)
print(b.sum(axis = 0))

print(b.cumsum(axis = 1))    # >> cumulative sum of each row
### axis = 0  >> vertically
### axis = 1  >> h

[[ 0.89875207  0.29345881  0.64355365]
 [ 0.54386692  0.57114328  0.52227134]]
3.4730460679
0.293458805718
0.898752071607

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


# Universal function

###  elementwise

In [44]:
B = np.arange(3)

print(np.exp(B))

print(np.sqrt(B))




[ 1.          2.71828183  7.3890561 ]
[ 0.          1.          1.41421356]


## One dimensional array can be slicing, iterate, indexing

## Multimensional

In [66]:
a = np.arange(10)**3
print(a)

## indexing

print(a[2:5])
a[:6:2] = -1000   # >> a[start:end:step]
print(a)

print(a[::-1])  # inverse the array

for i in a:
    print(i**(1/3.))
    
    
### Mutimensitional

def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype = int)
### 
print(b[2,3])

## b[row,column]

print(b[0:5,1])

### b[-1] = b[-1,:]

print(b[-1])


### dots(...) 用法
###  assume x is a rank5 array
## x[1,2,...] = x[1,2,3,4,5]

## x[4,...,5...] = x[4,:,:,5,:]


####  3D array

c = np.array([[[0,1,2],
            [10,12,13]],
          
           [[100,101,102],
           [110,112,113]]])

print(c.shape)

print(c[1,...])

print(c[...,2])

[  0   1   8  27  64 125 216 343 512 729]
[ 8 27 64]
[-1000     1 -1000    27 -1000   125   216   343   512   729]
[  729   512   343   216   125 -1000    27 -1000     1 -1000]
nan
1.0
nan
3.0
nan
5.0
6.0
7.0
8.0
9.0
23
[ 1 11 21 31 41]
[40 41 42 43]
(2, 2, 3)
[[100 101 102]
 [110 112 113]]
[[  2  13]
 [102 113]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:13: RuntimeWarning: invalid value encountered in power


## Iterating over multidimensional arrays is done with respec to first axis

#### np.flat  >> can iterate over all array  


In [70]:
for row in b:
    print(row)

print()
for element in b.flat:
    print(element)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


## Shape manipulation  

In [81]:
a = np.floor(10*np.random.random((3,4)))
print(a.shape)

### faltten the array

print(a.ravel())

###  
a.shape = (6,2)
### Transpose

a.T

### reshape >> if dimension is -1, the other dimensions are automatically calculated

a.reshape(3,-1)

(3, 4)
[ 0.  5.  4.  6.  1.  6.  0.  0.  6.  1.  9.  8.]


array([[ 0.,  5.,  4.,  6.],
       [ 1.,  6.,  0.,  0.],
       [ 6.,  1.,  9.,  8.]])

# Stacking array

In [96]:
a = np.floor(10*np.random.random((2,2)))
b=  np.floor(10*np.random.random((2,2)))

## vertical bind
print(np.vstack((a,b)))

## horizontal bind
print(np.hstack((a,b)))

### for 2D array, same as hstack
print(np.column_stack((a,b)))

a = np.array([4.,2.])
print(a[:,np.newaxis])  ### This allows to have a 2D columns vector

[[ 4.  6.]
 [ 3.  8.]
 [ 4.  3.]
 [ 0.  6.]]
[[ 4.  6.  4.  3.]
 [ 3.  8.  0.  6.]]
[[ 4.  6.  4.  3.]
 [ 3.  8.  0.  6.]]
[[ 4.]
 [ 2.]]


##  Array splitting

In [99]:
a = np.floor(10*np.random.random((2,12)))
print(a)
### horizontal split
print(np.hsplit(a,3))  ## split a into 3 equal array

print(np.hsplit(a,(3,4)))  ## split a after third and fourth column

[[ 0.  7.  5.  4.  7.  7.  9.  1.  8.  9.  9.  5.]
 [ 8.  0.  0.  6.  3.  1.  8.  2.  6.  2.  5.  6.]]
[array([[ 0.,  7.,  5.,  4.],
       [ 8.,  0.,  0.,  6.]]), array([[ 7.,  7.,  9.,  1.],
       [ 3.,  1.,  8.,  2.]]), array([[ 8.,  9.,  9.,  5.],
       [ 6.,  2.,  5.,  6.]])]
[array([[ 0.,  7.,  5.],
       [ 8.,  0.,  0.]]), array([[ 4.],
       [ 6.]]), array([[ 7.,  7.,  9.,  1.,  8.,  9.,  9.,  5.],
       [ 3.,  1.,  8.,  2.,  6.,  2.,  5.,  6.]])]


#  Copies And Views
### Three cases

In [108]:
### 1. No copy  >> simple assignment

a = np.arange(12)
b=  a
print(b is a)

### change b will also change a
b.shape = (3,4)
print(a.shape)


###  View or shallow copy
### the view method creates a new array object that looks at the same data
print()
c = a.view()
print(c is a)
print(c.base is a)

c.shape = (2,6)
print(a.shape)     ### not change
c[0,4] = 1234
print(a)     ## a change

### Slicing an array returns a view of it

s = a[:,1:3]
s[:] = 10

print(a)

### Deep copy  >> make a complete copy

### never change original data
d = a.copy()
d[0,0] = 999
print(a)


True
(3, 4)

False
True
(3, 4)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]
[[   0   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]


## Broadcast

In [113]:
### indexing

a = np.arange(12)**2
i = np.array([1,1,3,8,5])  ## array index
a[i]   ## extract value form index

array([ 1,  1,  9, 64, 25])

# Boolean Array

### USe boolean indexing to assign value

In [117]:
a = np.arange(12).reshape(3,4)
b=  a>4
print(a[b])   #  print a sequence of true value form a  
### this is very useful for assignment

a[b] = 0

print(a)


[ 5  6  7  8  9 10 11]
[[0 1 2 3]
 [4 0 0 0]
 [0 0 0 0]]


In [123]:
a = np.arange(12).reshape(3,4)
b1 = np.array([False,True,True])
b2 = np.array([True,False,True,False])

print(a[b1,:])   ## same as a[1:,]
print(a[b1])

print(a[:,b2])  ## same as [:,(0,2)]


[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2]
 [ 4  6]
 [ 8 10]]


# Linear Algebra

In [170]:
a = np.array([[1.0,2.0],[3.0,4.0]])
print(a, end = "\n\n")

print(a.transpose(), "\n")

print(np.linalg.inv(a),"\n")

## I matrix  >> unit matrix

u = np.eye(2)
print(u,"\n")

## matrix product  >> matrix 矩陣相乘,非內積
j = np.array([[0.0,-1.0],[1.0,0.0]])

print(np.dot(j,j),'\n')

## solve linear equation

y = np.array([[5.],[7.]])

np.linalg.solve(a,y)

[[ 1.  2.]
 [ 3.  4.]]

[[ 1.  3.]
 [ 2.  4.]] 

[[-2.   1. ]
 [ 1.5 -0.5]] 

[[ 1.  0.]
 [ 0.  1.]] 

[[-1.  0.]
 [ 0. -1.]] 



array([[-3.],
       [ 4.]])

# Matrix

In [171]:
A = np.matrix("1.0,2.0;3.0,4.0")
print(type(A))

print(A.T,"\n")

X  = np.matrix('5.0,7.0')
Y = X.T
print(Y,"\n")

### matrix multiplication

print(A*Y)  ## Equal to np.dot(A,Y)

## solve linear equation
np.linalg.solve(A,Y)



<class 'numpy.matrixlib.defmatrix.matrix'>
[[ 1.  3.]
 [ 2.  4.]] 

[[ 5.]
 [ 7.]] 

[[ 19.]
 [ 43.]]


matrix([[-3.],
        [ 4.]])

# Compare array and Matrix

### Slicing numpy doesn't make a copy of the data, slicing provieds a new view of the same data

### A slice of a matrix will always produce a matrix

### A slice of a matrix could produce a lower level array

In [176]:
A = np.arange(12)
A.shape = (3,4)
M = np.mat(A.copy())

print(type(A)," ",type(M))

print(A,"\n")

print(M)

<class 'numpy.ndarray'>   <class 'numpy.matrixlib.defmatrix.matrix'>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [180]:
print(A[:]);print(A[:].shape,'\n')

print(M[:]); print(M[:].shape,'\n')

print(A[:,1]); print(A[:1].shape,'\n')

print(M[:,1]);print(M[:,1].shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4) 

[1 5 9]
(1, 4) 

[[1]
 [5]
 [9]]
(3, 1)


# Extract specific part of array

In [184]:
print(A[:,[1,3]],'\n')   ## Extract column 1 and 3

print(A[:,].take([1,3],axis = 1),'\n')

## if we want to skip the first row

print(A[1:,].take([1,3],axis = 1))

[[ 1  3]
 [ 5  7]
 [ 9 11]] 

[[ 1  3]
 [ 5  7]
 [ 9 11]] 

[[ 5  7]
 [ 9 11]]


In [186]:
### example: retain all columns where first row is greater than 1

A[0,:]>1

A[:,A[0,:]>1]

### Matrix slicing >> use "A"

M[:,M.A[0,:]>1]


array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

# Tricks and Tips

- Automatic Reshaping >> When change the dimension of an array, can omit one of the size which will be deduced automatically

In [194]:
a = np.arange(30)
a.shape = (2,-1,3)
a.shape

print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
